# This file sets up a CMakeCache for the llvm build for rift

set(LLVM_ENABLE_PROJECTS "clang;lld" CACHE STRING "")
set(LLVM_ENABLE_RUNTIMES "libc" CACHE STRING "")
set(LLVM_TARGETS_TO_BUILD "X86;ARM;AArch64;RISCV" CACHE STRING "")

set(LLVM_INSTALL_TOOLCHAIN_ONLY OFF CACHE BOOL "")

#set(LLVM_DISTRIBUTION_COMPONENTS
#  clang
#  builtins
#  runtimes
#  CACHE STRING "")

# https://www.llvm.org/docs/CMake.html#llvm-related-variables
set(LLVM_BUILD_TOOLS        OFF CACHE BOOL "")
set(LLVM_ENABLE_BINDINGS    OFF CACHE BOOL "")
set(LLVM_ENABLE_OCAMLDOC    OFF CACHE BOOL "")
set(LLVM_ENABLE_LIBXML2     OFF CACHE BOOL "")
set(LLVM_ENABLE_LLD         ON  CACHE BOOL "")
set(LLVM_ENABLE_WARNINGS    OFF CACHE BOOL "")
set(LLVM_INCLUDE_BENCHMARKS OFF CACHE BOOL "")
set(LLVM_INCLUDE_DOCS       OFF CACHE BOOL "")
set(LLVM_INCLUDE_EXAMPLES   OFF CACHE BOOL "")
set(LLVM_INCLUDE_TESTS      OFF CACHE BOOL "")
set(LLVM_INCLUDE_TOOLS      ON  CACHE BOOL "")
set(LLVM_INCLUDE_UTILS      OFF CACHE BOOL "")
set(CLANG_BUILD_TOOLS       OFF CACHE BOOL "")


#  -DLLVM_INCLUDE_TOOLS=ON \
#  -DLLVM_BUILD_TOOLS=ON \
#  -DLLVM_USE_CRT_RELEASE=MD \
#  -DLLVM_USE_CRT_DEBUG=MDd