name: build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*.*.*'
  pull_request:
  workflow_call:

jobs:
  build-release:
    name: ${{ matrix.name }} (${{ matrix.config }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name: [Windows, Linux, MacOS]
        config: [Release]
        include:
          - name: Windows
            os: windows-latest
            cxx: clang-cl
            cc: clang-cl
          - name: Linux
            os: ubuntu-latest
            cxx: clang++
            cc: clang
          - name: MacOS
            os: macos-latest
            cxx: clang++
            cc: clang
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Init Submodules
        uses: snickerbockers/submodules-init@v4

      - name: Get CMake
        uses: lukka/get-cmake@latest

      - name: Build
        env:
          CC: ${{ matrix.cc }}
          CXX: ${{ matrix.cxx }}
        run: python build.py -c ${{ matrix.config }} --keep-build
        shell: sh

      - name: Install
        env:
          CC: ${{ matrix.cc }}
          CXX: ${{ matrix.cxx }}
        run: python build.py -c ${{ matrix.config }} --no-build -i install
        shell: sh

      - uses: actions/upload-artifact@v2
        with:
          name: LLVM-${{ matrix.name }}-${{ matrix.config }}
          path: install/${{ matrix.config }}
