name: build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-debug:
    name: ${{ matrix.name }} debug
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name: [windows, linux, macos]
        include:
          - name: windows
            os: windows-latest
            cxx: clang-cl
            cc: clang-cl
          - name: linux
            os: ubuntu-latest
            cxx: clang++
            cc: clang
          - name: macos
            os: macos-latest
            cxx: clang++
            cc: clang
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Init Submodules
        uses: snickerbockers/submodules-init@v4

      - name: Get CMake
        uses: lukka/get-cmake@latest

      - name: Cache llvm build
        uses: actions/cache@v2
        with:
          path: build
          key: llvm-${{ matrix.name }}-${{ env.GITHUB_SHA }}

      - name: Build
        env:
          CC: ${{ matrix.cc }}
          CXX: ${{ matrix.cxx }}
        run: python build.py -c Debug
        shell: sh

  build-release:
    needs: build-debug
    name: ${{ matrix.name }} release
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name: [windows, linux, macos]
        include:
          - name: windows
            os: windows-latest
            cxx: clang-cl
            cc: clang-cl
          - name: linux
            os: ubuntu-latest
            cxx: clang++
            cc: clang
          - name: macos
            os: macos-latest
            cxx: clang++
            cc: clang
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Init Submodules
        uses: snickerbockers/submodules-init@v4

      - name: Get CMake
        uses: lukka/get-cmake@latest

      - name: Cache llvm build
        uses: actions/cache@v2
        with:
          path: build
          key: llvm-${{ matrix.name }}-${{ env.GITHUB_SHA }}

      - name: Build
        env:
          CC: ${{ matrix.cc }}
          CXX: ${{ matrix.cxx }}
        run: python build.py -c Release
        shell: sh

  publish:
    needs: build-release
    name: Publish ${{ matrix.name }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        name: [windows, linux, macos]
    steps:
      - name: Download llvm build
        uses: actions/cache@v2
        with:
          path: build
          key: llvm-${{ matrix.name }}-${{ env.GITHUB_SHA }}

      - name: Package
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          path: 'build'
          filename: 'llvm-${{ matrix.name }}.zip'
          exclusions: '*.obj'

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: llvm-${{ matrix.name }}.zip
