name: publish-release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    uses: ./.github/workflows/build.yml

  publish:
    name: Publish ${{ matrix.name }}
    needs: build
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        name: [windows, linux, macos]
        include:
          - name: windows
            os: windows-latest
          - name: linux
            os: ubuntu-latest
          - name: macos
            os: macos-latest
    steps:
      - name: Download llvm build
        uses: actions/download-artifact@v2
        with:
          name: llvm-${{ matrix.name }}
          path: llvm

      - name: Package
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          path: 'llvm'
          filename: 'llvm-${{ matrix.name }}.zip'
          exclusions: '*.obj'

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: llvm-${{ matrix.name }}.zip
